version: "3.8"
services:
  #PHP Service
  php:
    build:
      context: .
      dockerfile: ./php.dockerfile
    image: php
    user: "1000:1000"
    container_name: lms_php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: php
      SERVICE_TAGS: dev
    working_dir: /var/www/html/
    volumes:
      - ../:/var/www/html/
    networks:
      - app-network

  #Nginx Service
  nginx:
    depends_on:
      - php
    build:
      context: .
      dockerfile: ./nginx.dockerfile
    container_name: lms_nginx
    restart: unless-stopped
    volumes:
      - ../:/var/www/html
    tty: true
    ports:
      - "8002:80"
    networks:
      - app-network
  
  #Mysql DB
  mysql:
    image: mysql:8.0
    container_name: lms_mysql
    restart: unless-stopped
    tty: true
    ports:
        - "33061:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - mysql:/mysql
    networks:
      - app-network

  # phpMyAdmin Service
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: lms_pma
    depends_on:
      - mysql
    ports:
      - 8082:80
    environment:
      PMA_ARBITRARY: 1
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      PMA_HOST: ${DB_HOST}
      PMA_PORT: ${DB_PORT}
    networks:
      - app-network

  #MailHog
  mailhog:
    image: mailhog/mailhog
    container_name: lms_mailhog
    ports:
        - "1025:1025"
        - "1085:8025"
    networks:
        - app-network

#Docker Networks
networks:
  app-network:
    name: app-network

volumes:
  mysql:
    driver: local