version: "3.8"
services:
  node:
    build:
      context: . # Ensure the path is correct relative to the docker-compose file
      dockerfile: ./node.dockerfile
    container_name: lms_node
    stdin_open: true
    restart: always
    working_dir: /app
    volumes:
      - ../:/app
      - /app/node_modules
    networks:
      - app-network
    environment:
      - CHOKIDAR_USEPOLLING=true
    expose: 
      - "5173" # Port for Vite
    ports: 
      - "5173:5173" # Vite usually runs on 5173, change if needed

  nginx:
    image: nginx:latest
    container_name: lms_node_nginx
    ports:
      - 8001:80
    working_dir: /app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../:/app
    depends_on:
      - node
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    name: app-network
    external: false