name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      # checkout action
      - uses: actions/checkout@v4

      # Frontend: build
      - name: Build Frontend
        working-directory: front-lms
        run: |
          npm install
          npm run build

      # prepare PHP 8.1
      - name: Configure PHP 8.1
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.1
          extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml

      # Backend: install composer dependencies and create artifact
      - name: Setup Backend
        working-directory: back-lms
        run: |
          composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader
          tar -czf back.tar.gz \
            --exclude=.git \
            --exclude=node_modules \
            --exclude=tests \
            --exclude=storage/logs/* \
            *
